### ISSUE TITLE
[1.18.2] Crash on world load - kotlin.UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by erunseelie** [Kneelawk/WiredRedstone#12]
Hi, I got this crash report on loading into a world I had recently started:
https://bytebin.lucko.me/iKku4MUszR

> kotlin.UninitializedPropertyAccessException: lateinit property GATE_PLACEMENT has not been initialized

I hadn't placed any WR items yet, so I'm not immediately sure what could have led to this.

**Comment by Kneelawk** [comment]
It looks like this error was encountered as NotEnoughCrashes was already generating a crash report for something else.

If you can give me any steps to reproduce, that would be much appreciated :)

**Comment by Kneelawk** [comment]
From what I can tell, this error was caused by NotEnoughCrashes attempting to generate a crash-report that involved rendering the world for some reason. However it attempted to render a world before having fully loaded all client-side assets, meaning that the shader had not been initialized yet.

The core-shader-based system I'm using for fancy gate placement ghosts is deprecated and I'm planning to replace it with a system that's more Iris/Canvas shader-friendly that hopefully shouldn't be as vulnerable to this problem. I'll close this when that system is implemented. It shouldn't be too hard to back-port that system to the 0.3.x-1.18.2 branch either.

**Comment by erunseelie** [comment]
Got it, sure. Sorry for no initial response, I was trying to see if it would happen again, as there weren't any real steps leading to the initial crash. If it reoccurs, I'll see if it happens without NotEnoughCrashes and follow up.

**Comment by Kneelawk** [comment]
Ok, the fix for this should be out in `v0.3.10+1.18.2` and `v0.4.13+1.19.2`.
