### ISSUE TITLE
Small visual bugs

### ISSUE THREAD

**Issue by ButterSus** [Kneelawk/WiredRedstone#44]
When the wire is located above some redstone components (such as comparators and repeaters), they are visually connected with it.
![area_render_31_](https://github.com/Kneelawk/WiredRedstone/assets/90126102/1f4733ee-c7eb-4750-b0e9-8240ffdde8f7)

It doesn't make sense.

**Comment by Kneelawk** [comment]
This is because wires connect to any vanilla block that says it outputs redstone. Since vanilla doesn't clarify which side the redstone is actually output from, Wired Redstone just assumes it's all sides.

What I could probably do here is add a tag like ~~`gate_redstone_connectivity`~~ that says that any blocks in it *only* connect on the sides, not on the top or bottom.

**Comment by Kneelawk** [comment]
This looks to be fixed in the development version:
![image](https://github.com/Kneelawk/WiredRedstone/assets/2180089/be89c191-575d-4f2c-9549-44624942ae10)

**Comment by Kneelawk** [comment]
The tag name I decided to go with was `wire_gate_connectable`.
