### ISSUE TITLE
1.19 Crash

### ISSUE THREAD

**Issue by Mattabase** [Kneelawk/WiredRedstone#9]
https://gist.github.com/75fb51579ff9c9eb0ab1743612e8aac6w

https://gist.github.com/f6e6265788757b90c27ca2506daddc44

**Comment by Aquaeyes** [comment]
[crash-2022-07-09_17.37.34-client.txt](https://github.com/Kneelawk/WiredRedstone/files/9076212/crash-2022-07-09_17.37.34-client.txt)
Was unable to open the first gist, uploading my own crash report just in case.

**Comment by PTOM76** [comment]
Running from runClient in Gradle (Intellij) succeeds, but when I try to put the jar in mods and run it, it seems to fail.
I guess there is something wrong with either LibMultiPart or LibNetworkStack.

**Comment by Kneelawk** [comment]
I've made an issue with LNS: https://github.com/AlexIIL/LibNetworkStack/issues/10

The Multi-Jar Creation Plugin used to separate different components of LNS, LBA, and LMP seems to be packaging dev jars instead of production jars.

~~For the time-being, here are some jars that fix the issue:~~

* ~~[https://cdn.discordapp.com/attachments/988316374709448784/995966670390710322/libblockatttributes-0.11.0-pre.1.2kneelawk.jar](https://cdn.discordapp.com/attachments/988316374709448784/995966670390710322/libblockatttributes-0.11.0-pre.1.2kneelawk.jar)~~
* ~~[https://cdn.discordapp.com/attachments/988316374709448784/995966670587838534/LibMultiPart-0.8.0-pre.1.3kneelawk.jar](https://cdn.discordapp.com/attachments/988316374709448784/995966670587838534/LibMultiPart-0.8.0-pre.1.3kneelawk.jar)~~
* ~~[https://cdn.discordapp.com/attachments/988316374709448784/995966670818517052/LibNetworkStack-0.7.1-pre.0.1kneelawk.jar](https://cdn.discordapp.com/attachments/988316374709448784/995966670818517052/LibNetworkStack-0.7.1-pre.0.1kneelawk.jar)~~

~~However, using these jars is not ideal, as they are not packaged correctly and only work due to coincidence.~~

Edit: No longer needed.

**Comment by Kneelawk** [comment]
This is fixed in release `v0.4.1+1.19`.

Modrinth: https://modrinth.com/mod/wiredredstone/version/0.4.1%2B1.19
CurseForge: https://www.curseforge.com/minecraft/mc-mods/wired-redstone/files/3869324
